### ISSUE TITLE
How to request same experience multiple time?

### ISSUE THREAD

**Issue by shukerullah** [tinypass/piano-sdk-for-android#11]
I am using composer experience in Tabs. Each tabs is page for me. I call `Composer.getInstance().getExperience(request, listeners, exception)` when page is created.

This is working fine for once but when I go back to previous page then listeners are not triggering. How do I request same experience again, Do I need to call `Composer.getInstance().getExperience(request, listeners, exception)` again when page is focused?

**Comment by DeKaN** [comment]
First, Android creates not only the current tab, but it also creates and keeps in memory several neighboring tabs. Are you sure to request experience for tab, which the user hasn't seen yet?

Without code, I can suggest only, but I think you're using local variables for `listeners`, which can be destroyed with fragment after the user has changed the tab.

**Comment by shukerullah** [comment]
I am requesting experience when tab is visible (You can see in code below). But each time it's creating new a request. Should it be a new request for each time page is viewed?

```
  @Override
  public void setUserVisibleHint(boolean visible) {
      super.setUserVisibleHint(visible);
      if (visible) {
          getExperience();
      }
  }
    
  private void getExperience() {
      ExperienceRequest.Builder builder = new ExperienceRequest.Builder();
      // ... Setup builder here...

      ExperienceRequest request = builder.build();
      Collection<EventTypeListener<? extends EventType>> listeners = Arrays.asList(
              (ShowLoginListener) event -> {
                  // Do something here
              },
              (ShowTemplateListener) event -> {
                  showTemplateController = ShowTemplateController.show((FragmentActivity)getCurrentActivity(), event, new ComposerJs() {
                      @JavascriptInterface
                      @Override
                      public void customEvent(@NonNull String eventData) {
                          // Do something here
                      }
                      @JavascriptInterface
                      @Override
                      public void login(@NonNull String eventData) {
                          // Do something here
                      }
                  });
              }
      );
      Composer.getInstance().getExperience(request, listeners, exception -> {
          // Exception: Do something about it
      });
  }
```

**Comment by DeKaN** [comment]
You can request an experience every time when you need it. If your case "we need to get experience every time when the user opens a specified page", then your code is correct.
You're store listeners in the local fragment variable, so Android removes them at fragment destroying. If you want to process result after that user lefts the tab, you should store them in the parent fragment/activity or inside the presenter

**Comment by shukerullah** [comment]
Thank you so much.
