### ISSUE TITLE
How to close showTemplateController? 

### ISSUE THREAD

**Issue by shukerullah** [tinypass/piano-sdk-for-android#12]
I am using `ShowTemplateController.show` on `ShowTemplateListener`. How to close template controller programmatically?

**Comment by DeKaN** [comment]
You should provide `jsInterface` to `ShowTemplateController.show`. After that, you can call `close` from JS in template or from your app's code via `jsInterface.close("some event data here")`

**Comment by shukerullah** [comment]
Thanks
