### ISSUE TITLE
Could not login with Google

### ISSUE THREAD

**Issue by njboro** [tinypass/piano-sdk-for-android#16]
Error 403: disallowed_useragent
Google can’t sign you in safely inside this app. You can use Google sign-in by visiting this app’s website in a browser like Safari or Chrome.

For your reference, sdk version v2.0.4
I am not handling with native google login. It is handled from Sign in Template.

**Comment by DeKaN** [comment]
Google and Facebook require to use the native sign in libs. So, you have to use [OAuth providers](https://github.com/tinypass/piano-sdk-for-android/tree/master/id#social-sign-in) for it

**Comment by njboro** [comment]
Kindly help me to make it work. Because, I am not getting it work with Native FB and Google sign in even I have added the codes mentioned in the read me [PIANO ID Readme](https://github.com/tinypass/piano-sdk-for-android/tree/master/id#social-sign-in) and [Doc](https://docs.piano.io/implementing-pianos-latest-sdk/#androidImplementation) . 
I have also configured my app in Facebook and Google.

**Comment by DeKaN** [comment]
1. Add dependecy (`io.piano.android:id-oauth-google` for Google, `io.piano.android:id-oauth-facebook` for Facebook) as mentioned in readme
1. Add to Piano ID initialization `with(GoogleOAuthProvider())` and/or `with(FacebookOAuthProvider())` (see [sample ](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample-ktx/src/main/java/io/piano/sample/PianoSampleApplication.kt#L32-L33))

Have you done it?

**Comment by njboro** [comment]
Yes, I already added those.

While Login with Google, actually I am getting an exception : 
**com.google.android.gms.common.api.ApiException: 10:**

**Comment by DeKaN** [comment]
`com.google.android.gms.common.api.ApiException: 10` means `Google Console project configured incorrectly`
If you've done using [the guide](https://developers.google.com/identity/sign-in/android/start-integrating#configure_a_project) and you're getting this error, please write to support. They will help you with the configuration.

BTW, the most common problem is "incorrect app certificate hash in console"

**Comment by njboro** [comment]
Hi, do we need to set Client ID in native for Google sign in ?

**Comment by DeKaN** [comment]
@njboro You should set web client id at Piano dashboard and set package name and sha1 in Google Console

**Comment by njboro** [comment]
Ok, Thank you.

**Comment by oussemaRidene** [comment]
Hi, I'm using flutter, and I've already setup the piano id in the native part,
I initialized the piano in my application class : 
`PianoId.init(PianoId.ENDPOINT_PRODUCTION, "0ONaLve1su").with(new GoogleOAuthProvider());`
 now I want to send the user information to piano  when the use select his account from google signin popup.
 how can I do this ?

**Comment by DeKaN** [comment]
Hi, @oussemaRidene
You should use similar code for [registering receiver](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample/src/main/java/io/piano/sample/MainActivity.kt#L43-L53) and [starting login process](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample/src/main/java/io/piano/sample/MainActivity.kt#L66) in native part. Another option is using `PluginRegistry.ActivityResultListener` with manual parsing of result

**Comment by oussemaRidene** [comment]
Hi @DeKaN thank you for your answer, it solves the problem but I had a blank page after loading.
my code : 
`authResult.launch(
                        PianoId.signIn()
                                .widget("login")
                );`

**Comment by DeKaN** [comment]
Hi, @oussemaRidene
Use [this](https://developer.chrome.com/docs/devtools/remote-debugging/) instruction for checking webview issues (don't forget to add [code](https://github.com/tinypass/piano-sdk-for-android/blob/71207d8192d9584b770d837622ac8797056e8fca/sample/src/main/java/io/piano/sample/PianoSampleApplication.kt#L27-L30)). You can provide all results via already opened ticket to support :)
