### ISSUE TITLE
Unable to get the Country Code from the Piano Events

### ISSUE THREAD

**Issue by chungngailun** [tinypass/piano-sdk-for-android#18]
I found that there is a Json parsing issue in the class `EventExecutionContext`

On line 46, it's trying to parse the value of country code. The key is using **country**
`eventExecutionContext.country = eventExecutionContextJson.optString("country");`

However, in the Json of `eventExecutionContext`, the key for the country code is **countryCode**
`{"executionId":"N\/A","experienceId":"N\/A","experienceVersion":null,"trackingId":"N\/A","splitTests":[],"currentMeterName":"DefaultMeter","activeMeters":[],"allMeters":[{"meterName":"DefaultMeter","views":5,"viewsLeft":null,"maxViews":null,"totalViews":5}],"user":{"uid":"anon","firstName":"N\/A","lastName":"N\/A","email":"N\/A"},"region":"HCW","countryCode":"HK","accessList":[],"userSegments":{}}"`

As a result, we cannot get the value of the country code from the event. Please help to fix it in next release. Thank you so much!

**Comment by DeKaN** [comment]
It seems you use version 1.5.0 or older. Did you try to update?

**Comment by chungngailun** [comment]
@DeKaN Yes, you're right. The SDK version we used is too old. We upgraded to 2.0.2 for the Composer then it works fine now. Thanks!
