### ISSUE TITLE
How can we differentiate user did Registration or Sign in ?

### ISSUE THREAD

**Issue by njboro** [tinypass/piano-sdk-for-android#19]
I wanted to know after sign in or sign up success method callback to onActivityResult().

**Comment by njboro** [comment]
wan to know after sign in or sign up success method callback to onActivityResult() - is there anyway to understand if user does Sign in or Sign up from Sign Up Piano template?

**Comment by DeKaN** [comment]
There is no information about it at this moment

**Comment by DeKaN** [comment]
Will be part of the next release

**Comment by DeKaN** [comment]
@njboro Version 2.1.0 has been released. See [example](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample-ktx/src/main/java/io/piano/sample/MainActivity.kt#L47)
