### ISSUE TITLE
How can I find PIANO_AID

### ISSUE THREAD

**Issue by fairlyNguyen** [tinypass/piano-sdk-for-android#2]
I download sample application but I don't know how can I find PIANO_AID.

**Comment by ampirator** [comment]
It's "Application ID" (https://docs.piano.io/glossary-definition/application-id/) can be obtained on publisher dashboard.
prod: https://dashboard.piano.io
sandbox: https://sandbox.piano.io

**Comment by fairlyNguyen** [comment]
@ampirator ,
Can I use this application to run in Piano SDK for native app?

**Comment by ampirator** [comment]
As i see your application doesn't support "Piano Composer".
