### ISSUE TITLE
Json parsing error on Composer

### ISSUE THREAD

**Issue by woodyLam** [tinypass/piano-sdk-for-android#20]
when I submitting experience, the field `region` in JSON response will be null and `region` is not optional in `EventExecutionContext`,  it will be throw exception on moshi, so that I can't get the values of the event.
In my case, if i my country was Malaysia, region will be null. But not null in US or HK.

Composer version: 2.0.2
Error:  `com.squareup.moshi.JsonDataException: Non-null value 'region' was null at $.models.result.events[0].eventExecutionContext.region`

**Comment by DeKaN** [comment]
Fixed in 2.0.5. `region` field become nullable
