### ISSUE TITLE
How can I Set the stage directive element value ?

### ISSUE THREAD

**Issue by oussemaRidene** [tinypass/piano-sdk-for-android#29]

**Comment by DeKaN** [comment]
Use `PianoId.signIn().stage("...")`

**Comment by oussemaRidene** [comment]
Thank you for your quick reply,
I already read the documentation, I found that I need to use .stage("..."),
but i have read all your SDK source code and there is no trace of this function
I tried to use it and here is the result:
`MainActivity.kt: (123, 38): Unresolved reference: stage
FAILURE: Build failed with an exception.`

**Comment by DeKaN** [comment]
@oussemaRidene Check [this](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample/src/main/java/io/piano/sample/MainActivity.kt#L67) line and just add `stage` as mentioned in my previous comment

**Comment by oussemaRidene** [comment]
@DeKaN that's what I did
**Code :** 
`authResult.launch(
                    PianoId.signIn().stage("website")
                );`
                
**Error :** 
`MainActivity.kt: (113, 38): Unresolved reference: stage`

**Piano dependencies :** 
`    implementation("io.piano.android:id:2.4.0")
    implementation("io.piano.android:id-oauth-google:2.4.0")
    implementation("io.piano.android:id-oauth-facebook:2.4.0")`

**Comment by DeKaN** [comment]
@oussemaRidene Support for stage was added in 2.6.0, just update to the latest version

**Comment by oussemaRidene** [comment]
it works, thank you
