### ISSUE TITLE
Piano ID authentication hangs after entering user and password

### ISSUE THREAD

**Issue by mihaelaLo** [tinypass/piano-sdk-for-android#3]
I have installed the sample application and replaced the AID. I encountered two problems:

1. In PianoIdClient the deploymentHost returned is for production even if apiEndpointUrl is sandbox.tinypass.com. Hardcoded the deploymentHost to always be sandbox. 
`deploymentHost = https://sandbox.tinypass.com/`
2. The above step resolved the problem and the login page appears. Entering the correct user and password does nothing. If I select the box "Stay logged in" then an empty page appears. The url that is loaded is:
`https://sandbox.tinypass.com/id/api/v1/identity/vxauth/authorize?client_id={our_client_id}&response_type=token&redirect_uri=piano.id.oauth.{our_client_id}%3A%2F%2Fsuccess&force_redirect=1`

Same thing happens on web also: loading the above url first displays the login page and login button does nothing (no error, no success), then checking keep me logged in no page is loaded. Postman shows that response is a html page that seems the piano loading page: https://gist.github.com/mihaelaLo/4012530bca5163315a8a6e92b7aa0e68

What I am missing? Thanks

**Comment by mihaelaLo** [comment]
it seems a problem with the activity using chrome tabs: PianoIdOAuthRedirectActivity. Modifying the PianoIdClient to use PianoIdOAuthActivity that uses webviews (don't forget to change the redirect uri also) will make the app work as expected. Seems that the one with chrome tabs never returns

**Comment by DeKaN** [comment]
Closing as an old and obsolete issue. If you'll face with this issue, please reopen it.
