### ISSUE TITLE
Facebook Authentification failed

### ISSUE THREAD

**Issue by oussemaRidene** [tinypass/piano-sdk-for-android#30]
I was using Paino-sdk 2.4.0, everything works fine, and when I upgraded  to 2.6.2 to fix the stage issue, I encountered facebook authentication problem, when I press the facebook button, the Oauth screen closes for no reason

**Comment by DeKaN** [comment]
Can you share FB errors from logcat?
By the way, check [this](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample/build.gradle.kts#L34-L36) section  in Gradle script and [this](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample/src/main/AndroidManifest.xml#L41-L62) section in AndroidManifest. Pay attention to added `FB_APP_TOKEN`

**Comment by oussemaRidene** [comment]
I didn't notice that there are modifications to be made in the gradle script, it's ok now it works thank you
