### ISSUE TITLE
DeploymentHost gets overridden internally

### ISSUE THREAD

**Issue by michael-bichlmeier-sz** [tinypass/piano-sdk-for-android#42]
As Piano is listed on some AdBlocker apps we want to set a custom endpoint to avoid customer issues not seeing the login screen for example. 
Web and iOS worked so far but in the Android SDK there is no possibility to do that as the passed endpoint in `PianoId.init` is not used as host for the upcoming calls. This host gets overridden internally after initializing `PianoIdClient`. 

I opened a PR ( #43 ) which should give more customization. 
I wondered if it's really needed to override the `deploymentHost` in your `init` block of `PianoIdClient`? You are already passing the endpoint, so why is there a need to request the host again? If the call fails, the passed `endpoint` is used instead.

**Comment by DeKaN** [comment]
Hi @michael-bichlmeier-sz , 

`deployment host` is important part of domain whitelabeling and it can be used for your case without any changes inside SDK.
Just configure domain whitelabeling via Piano support, set the domain as `deployment host` at dashboard, and set the domain as endpoint for SDK.

**Comment by michael-bichlmeier-sz** [comment]
Hi @DeKaN , thanks for the quick reply. I didn't know that this setting exist in the dashboard. 🙏 

Can you give me some details why setting the endpoint programmatically is not enough and you need to do an api call to get the deployment host from the dashboard?

I hope your hint fixes the problem. I will give you feedback as soon as I have new information on that.

**Comment by DeKaN** [comment]
Hi @michael-bichlmeier-sz ,

We decided to make similar behavior between SDKs, so `deployment host` API will not be used for custom domains from the next version.

**Comment by DeKaN** [comment]
Released as part of 2.9.0

**Comment by michael-bichlmeier-sz** [comment]
Thank you @DeKaN . This sounds very good and thanks for the update 🙏
