### ISSUE TITLE
Template is not displayed with full height

### ISSUE THREAD

**Issue by trientran** [tinypass/piano-sdk-for-android#46]
![Screenshot_20240220_130018](https://github.com/tinypass/piano-sdk-for-android/assets/22525559/af448326-6708-4365-8c1e-d2333ddeab67)

I just tried running the sample app with our app ID and template. In the Composer Screen, the template is successfully shown as an alert dialog but the dialog size is not displayed in full height. As the alert dialog is internally implemented by the SDK, I have not found out how I can make it display full height yet. 

Am I missing something?

**Comment by DeKaN** [comment]
`androidx.appcompat.app.AlertDialog` / `androidx.appcompat.app.AppCompatDialogFragment` size depends on its contents. We put only WebView inside it, which size depends on html content of your template.
Did you try to specify height in template html code?

**Comment by trientran** [comment]
Thanks for your reply. The html content in the screenshot is quite reasonable and I can scroll up and down to see the whole content. In this case, should the dialog automatically expand to capture the whole webview content like you said? It's not so simple as setting a fixed height in the template HTML code as different screen sizes scale differently.

**Comment by trientran** [comment]
Perhaps you can try running the sample app on your side to compare?

**Comment by DeKaN** [comment]
Our policy requires that issues with any client-related data (AID / templates code / composer canvas data / etc.) should be processed via [support](https://support.piano.io). Please report there with a link to this GitHub issue

**Comment by trientran** [comment]
All good. We managed to resolve it!
