### ISSUE TITLE
PianoIdActivity does not show the HTML when opening it for a second time

### ISSUE THREAD

**Issue by fabiorbap** [tinypass/piano-sdk-for-android#48]
I'm using the `io.piano.android:id`, `io.piano.android:id-oauth-google` and `io.piano.android:id-oauth-facebook` libraries, version `2.10.0` in my app.
I'm using a VPN to test my app.
When I open the PianoIdActivity through `PianoId.getInstance().signIn()`, the screen shows properly with the template for the first time. However, when I try opening the screen **for the second time** in the same session, the screen shows blank.
The app is a WebView wrapper, and I noticed that when the screen shows blank, I get the following error in the console:

```
[INFO:CONSOLE(1)] "Uncaught TypeError: PianoIDMobileSDK.messageCallback is not a function", source: https://id-eu.piano.io/id/api/v1/identity/vxauth/authorize?response_type=token&client_id=z7Bat5xusu&force_redirect=1&disable_sign_up=false&redirect_uri=piano.id.oauth.z7Bat5xusu%3A%2F%2Fsuccess&is_sdk=true&oauth_providers=google%2Cfacebook (1)
```

In the app, I am not using any `PianoIDMobileSDK.messageCallback`, so I imagine this is called from within the SDK, and I think that's what's causing the screen not to render for the second time.

Another weird thing is that I also get this message in the console, even though the SDK is in the latest version:

```
[INFO:CONSOLE(1)] "Please update your Piano ID SDK version to the latest.", source: https://cdn.piano.io/id/1.50.4/main.js (1)
```

How could I fix this issue? Why I'm getting `Uncaught TypeError: PianoIDMobileSDK.messageCallback is not a function` error?

Thank you

**Comment by DeKaN** [comment]
SDK uses Piano ID login webpage. Maybe you've misconfigured it on dashboard? I recommend you ask about the error via [support](https://support.piano.io/) because we need to know AID for ID team

**Comment by fabiorbap** [comment]
Thanks @DeKaN , I just sent it to the support

**Comment by fabiorbap** [comment]
To whom it might concern: the problem was that the Deployment Host in the **Sandbox** environment was wrong. Changing it to the right on `https://sandbox.tinypass.com/` fixed the problem.
