### ISSUE TITLE
Improvement idea: remove context from PianoIdClient and make signIn accept context or fragment

### ISSUE THREAD

**Issue by mihaelaLo** [tinypass/piano-sdk-for-android#5]
Right now PianoIdClient requires context in constructor. Context is only used to display a toast and start the login activity. No need to store it in the client, that without context can become singleton. If you call sign in from different places throughout the app, there is no need to insatiate more clients.
Also starting the activity is limited right now for activities. Make it open for fragments too. If we call context.startActivityForResult, only the activity will receive the call on onActivityResult. Calling it from fragments will be fragment.startActivityForResult.

**Comment by DeKaN** [comment]
Now `PianoIdClient` doesn't store context and  `sign in` call ends by `getIntent(context: Context)`. You can use result Intent to start the activity with your `request code` from your fragment/activity
