### ISSUE TITLE
2.0.0-beta01 does not contain ShowTemplateController

### ISSUE THREAD

**Issue by ccrates** [tinypass/piano-sdk-for-android#6]
Following [this documentation](https://docs.piano.io/implementing-pianos-latest-sdk/) as well as look at your sample [ComposerActivity](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample/src/main/java/io/piano/android/sample/feature/composer/ComposerActivity.java), both reference the `ShowTemplateController`.

Unfortunately I am unable to resolve this class, or indeed the import from `io.piano.android.composer.showtemplate`. Is this a known issue, or just a quirk on my machine?

**Comment by DeKaN** [comment]
@ccrates Did you add dependency to `composer-show-template` artifact?

**Comment by ccrates** [comment]
@DeKaN That has solved it. Thank you for your prompt response!

I re-checked the documentation to see if I'd missed anything and this dependency wasn't mentioned. Could it be added?

**Comment by DeKaN** [comment]
All artifacts listed in README here, but I'll ask to add it into documentation
